// Human and agent summaries generated by `obks export`:
//  - tokens/exports/html/brand-at-a-glance.html (open in any browser, no setup)
//  - tokens/exports/agent/ui-brief.md (compact design brief for AI agents)
import fs from "node:fs";
import path from "node:path";
import { effectiveMaturity, listFiles } from "./fs-kit.js";
import { cssVarName, evaluateContrast, toCssValue, toPosix } from "./tokens.js";
import { resolveVisibility } from "./publication.js";

const esc = (s) =>
  String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");

const fmtRatio = (r) => `${(Math.floor(r * 100) / 100).toFixed(2)}:1`;

function logoFiles(kitRoot) {
  return listFiles(path.join(kitRoot, "assets", "logo"))
    .map((f) => toPosix(path.relative(kitRoot, f)))
    .filter((f) => /\.(svg|png|jpe?g|webp|ico)$/i.test(f));
}

const MIME = { svg: "image/svg+xml", png: "image/png", jpg: "image/jpeg", jpeg: "image/jpeg", webp: "image/webp", ico: "image/x-icon" };

// Logos larger than this are linked from the brand page instead of embedded.
export const MAX_EMBED_BYTES = 200 * 1024;

// Embeds a logo so the page still works when emailed or moved. SVG line endings are
// normalized so Windows and Linux checkouts produce the same page.
function logoBuffer(kitRoot, rel) {
  const buf = fs.readFileSync(path.join(kitRoot, rel));
  return rel.toLowerCase().endsWith(".svg") ? Buffer.from(buf.toString("utf8").replace(/\r\n/g, "\n")) : buf;
}

export function logoDataUri(kitRoot, rel) {
  const ext = rel.split(".").pop().toLowerCase();
  return `data:${MIME[ext]};base64,${logoBuffer(kitRoot, rel).toString("base64")}`;
}

function themeColor(tokens, theme, p) {
  const t = (tokens.themes[theme] || []).find((x) => x.path === p);
  return t?.token.value;
}

// Picks readable label text (near-black or white) for a swatch.
function labelOn(hex) {
  const h = hex.replace("#", "");
  const full = h.length === 3 ? h.split("").map((c) => c + c).join("") : h.slice(0, 6);
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(full.slice(i, i + 2), 16));
  return r * 0.299 + g * 0.587 + b * 0.114 > 150 ? "#111111" : "#FFFFFF";
}

export function buildBrandAtAGlance(kitRoot, manifest, tokens) {
  const colors = tokens.base.filter((t) => t.token.type === "color");
  const fonts = tokens.base.filter((t) => t.token.type === "fontFamily");
  const sizes = tokens.base.filter((t) => t.token.type === "dimension" && t.group === "fontSize");
  const themes = Object.keys(tokens.themes).sort();
  const contrast = evaluateContrast(manifest, tokens);
  const logos = logoFiles(kitRoot);
  const visibility = resolveVisibility(manifest);
  const parent = manifest.hierarchy?.parent;

  const swatch = ({ path: p, token }) => {
    const themeCells = themes
      .map((th) => {
        const v = themeColor(tokens, th, p);
        return v
          ? `<div class="mini" style="background:${esc(v)};color:${labelOn(v)}">${esc(th)} ${esc(v)}</div>`
          : "";
      })
      .join("");
    return `<div class="card">
      <div class="chip" style="background:${esc(token.value)};color:${labelOn(token.value)}">${esc(token.value)}</div>
      <div class="meta"><strong>${esc(p)}</strong>
        <code>${esc(cssVarName(manifest, ...p.split(".")))}</code>
        <p>${esc(token.description || "")}</p>
        ${token.usage?.avoid?.length ? `<p class="avoid">Avoid: ${esc(token.usage.avoid.join("; "))}</p>` : ""}
        ${themeCells}
      </div>
    </div>`;
  };

  const contrastRows = contrast
    .map((r) => {
      if (r.error) {
        return `<tr><td>${esc(r.theme)}</td><td colspan="4">${esc(r.foreground)} on ${esc(r.background)}</td><td class="fail">${esc(r.error)}</td></tr>`;
      }
      return `<tr>
        <td>${esc(r.theme)}</td>
        <td><span class="pair" style="background:${esc(r.bgValue)};color:${esc(r.fgValue)}">Aa</span> ${esc(r.foreground)} on ${esc(r.background)}</td>
        <td>${esc(r.use)}</td>
        <td>${fmtRatio(r.ratio)}</td>
        <td>${r.min}:1</td>
        <td class="${r.pass ? "pass" : "fail"}">${r.pass ? "Pass" : "Fail"}</td>
      </tr>`;
    })
    .join("\n");

  const fontRows = fonts
    .map(
      ({ path: p, token }) =>
        `<div class="font"><p style="font-family:${esc(toCssValue(token))}">The quick brown fox jumps over the lazy dog. 0123456789</p><small><strong>${esc(p)}</strong>: ${esc(toCssValue(token))}</small></div>`
    )
    .join("\n");

  const sizeRows = sizes
    .map(
      ({ name, token }) =>
        `<div style="font-size:${esc(token.value)};line-height:1.3">${esc(name)} (${esc(token.value)})</div>`
    )
    .join("\n");

  // Small logos are embedded so the page works on its own; large ones are linked so
  // the page stays small (the link works when the page is opened inside the kit).
  const logoCells = logos
    .map((f) => {
      const bg = `logo-bg${/reversed|white|dark/i.test(f) ? " dark" : ""}`;
      const bytes = logoBuffer(kitRoot, f).length;
      const inner =
        bytes <= MAX_EMBED_BYTES
          ? `<img src="${logoDataUri(kitRoot, f)}" alt="${esc(path.posix.basename(f))}">`
          : `<a href="../../../${esc(f)}">Open ${esc(path.posix.basename(f))} (${Math.round(bytes / 1024)} KB, too large to embed)</a>`;
      return `<figure><div class="${bg}">${inner}</div><figcaption>${esc(f)}</figcaption></figure>`;
    })
    .join("\n");

  const visibilityText = {
    private: "Private. Do not share files from this kit outside the organization.",
    partner: "Partner. Only the files listed in brandkit.yaml (publication.includedPaths) may be shared with partners.",
    public: "Public. The files listed in brandkit.yaml (publication.includedPaths) may be shared publicly, for example in a press kit.",
  }[visibility];

  return `<!DOCTYPE html>
<!-- Generated by obks export. Do not edit by hand. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(manifest.brand.displayName)} brand at a glance</title>
<style>
  body { font-family: system-ui, -apple-system, "Segoe UI", sans-serif; margin: 0; padding: 24px 16px; color: #1a1a1a; background: #fafafa; }
  main { max-width: 1040px; margin: 0 auto; }
  h1 { margin: 0 0 4px; } h2 { margin-top: 40px; border-bottom: 1px solid #ddd; padding-bottom: 6px; }
  .sub { color: #555; margin: 0 0 16px; }
  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(230px, 1fr)); gap: 16px; }
  .card { background: #fff; border: 1px solid #e3e3e3; border-radius: 10px; overflow: hidden; }
  .chip { border-bottom: 1px solid #e3e3e3; height: 88px; display: flex; align-items: flex-end; padding: 8px 10px; font: 600 14px ui-monospace, monospace; }
  .meta { padding: 10px; font-size: 14px; } .meta p { margin: 6px 0; color: #444; }
  .meta code { display: block; font-size: 12px; color: #555; word-break: break-all; }
  .avoid { color: #8a1c1c !important; } .mini { margin-top: 6px; padding: 4px 8px; border-radius: 6px; font: 12px ui-monospace, monospace; }
  table { width: 100%; border-collapse: collapse; background: #fff; font-size: 14px; }
  th, td { text-align: left; padding: 8px; border-bottom: 1px solid #eee; vertical-align: middle; }
  .pair { display: inline-block; padding: 2px 8px; border-radius: 4px; font-weight: 700; border: 1px solid #ccc; }
  .pass { color: #116329; font-weight: 700; } .fail { color: #a40e26; font-weight: 700; }
  .font { background: #fff; border: 1px solid #e3e3e3; border-radius: 10px; padding: 12px; margin-bottom: 12px; } .font p { font-size: 22px; margin: 0 0 6px; }
  figure { margin: 0; } .logo-bg { background: #fff; border: 1px solid #e3e3e3; border-radius: 10px; padding: 20px; display: flex; justify-content: center; align-items: center; height: 120px; }
  .logo-bg.dark { background: #1f2937; } .logo-bg img { max-height: 100%; max-width: 100%; } figcaption { font-size: 12px; color: #555; margin-top: 6px; word-break: break-all; }
  .note { background: #fff8e1; border: 1px solid #f0d78c; border-radius: 10px; padding: 12px; }
  .scroll { overflow-x: auto; }
</style>
</head>
<body>
<main>
  <h1>${esc(manifest.brand.displayName)}</h1>
  <p class="sub">Brand at a glance. Maturity: ${esc(effectiveMaturity(manifest))}. Role: ${esc(manifest.role)}.${parent ? ` Part of the ${esc(parent.brandId)} brand family.` : ""}</p>
  <p class="note"><strong>Sharing:</strong> ${esc(visibilityText)}${manifest.contacts?.security ? ` Report look-alike sites or emails: ${esc(manifest.contacts.security)}` : ""}</p>

  <h2>Colors</h2>
  <div class="grid">
${colors.map(swatch).join("\n")}
  </div>

  ${contrast.length ? `<h2>Color pairs checked for readability (WCAG)</h2>
  <div class="scroll"><table>
    <thead><tr><th>Theme</th><th>Pair</th><th>Use</th><th>Contrast</th><th>Needs</th><th>Result</th></tr></thead>
    <tbody>
${contrastRows}
    </tbody>
  </table></div>` : ""}

  ${fonts.length ? `<h2>Typography</h2>\n${fontRows}\n${sizeRows}` : ""}

  ${logos.length ? `<h2>Logos</h2>\n  <div class="grid">\n${logoCells}\n  </div>` : ""}

  <p class="sub" style="margin-top:40px">Generated by <code>obks export</code> from <code>tokens/</code> and <code>brandkit.yaml</code>. Edit those files, not this page.</p>
</main>
</body>
</html>
`;
}

export function buildUiBrief(kitRoot, manifest, tokens) {
  const lines = [
    `# ${manifest.brand.displayName} UI brief (generated)`,
    "",
    "> Generated by `obks export`. Do not edit by hand. Use only the values below; never invent new colors or fonts.",
    "",
    `- Brand id: \`${manifest.brand.id}\` (${manifest.role}, ${effectiveMaturity(manifest)})`,
    `- CSS: import \`tokens/exports/css/variables.css\` and use the variables, not raw hex.`,
  ];
  if (manifest.hierarchy?.parent) {
    lines.push(`- Inherits from parent kit \`${manifest.hierarchy.parent.brandId}\`. Do not add a second primary color.`);
  }
  lines.push("");

  const byType = (type) => tokens.base.filter((t) => t.token.type === type);
  const table = (entries, withUsage) => {
    const rows = ["| Token | CSS variable | Value | Use for | Avoid |", "|---|---|---|---|---|"];
    for (const { group, name, path: p, token } of entries) {
      const use = withUsage ? token.usage?.contexts?.join("; ") || token.description || "" : token.description || "";
      const avoid = token.usage?.avoid?.join("; ") || "";
      const cell = (s) => String(s).replace(/\|/g, "\\|");
      rows.push(`| \`${p}\` | \`${cssVarName(manifest, group, name)}\` | \`${cell(toCssValue(token) ?? token.value)}\` | ${cell(use)} | ${cell(avoid)} |`);
    }
    return rows;
  };

  const colors = byType("color");
  if (colors.length) lines.push("## Colors", "", ...table(colors, true), "");

  for (const theme of Object.keys(tokens.themes).sort()) {
    lines.push(`## Theme: ${theme}`, "", `Applied with \`data-theme="${theme}"\`${theme === "dark" ? " or the system dark-mode setting" : ""}. Overrides:`, "");
    for (const { path: p, token } of tokens.themes[theme]) {
      lines.push(`- \`${p}\` becomes \`${token.value}\``);
    }
    lines.push("");
  }

  const type = [...byType("fontFamily"), ...byType("fontWeight"), ...byType("dimension"), ...byType("number"), ...byType("duration")];
  if (type.length) lines.push("## Type, spacing, and motion", "", ...table(type, false), "");

  const contrast = evaluateContrast(manifest, tokens).filter((r) => !r.error);
  if (contrast.length) {
    lines.push("## Approved text and background pairs", "");
    for (const r of contrast) {
      lines.push(`- ${r.theme}: \`${r.foreground}\` on \`${r.background}\` = ${fmtRatio(r.ratio)} (${r.pass ? "passes" : "FAILS"} ${r.min}:1)${r.use ? `, for ${r.use}` : ""}`);
    }
    lines.push("", "Only pair text and backgrounds from this list unless you check contrast first.", "");
  }

  const logos = logoFiles(kitRoot);
  if (logos.length) {
    lines.push("## Logos", "", ...logos.map((f) => `- \`${f}\``), "", "Follow `visual/logo.md` for clear space and colorways. Never redraw, recolor, or stretch a logo.", "");
  }

  lines.push(
    "## Guardrails",
    "",
    "- Meet WCAG 2.2 AA: 4.5:1 for normal text, 3:1 for large text and UI components.",
    "- Do not convey meaning by color alone.",
    `- Sharing: this kit is **${resolveVisibility(manifest)}**. Check \`publication\` in \`brandkit.yaml\` before sending files outside the organization.`,
    ""
  );
  return lines.join("\n");
}
