/** Generated by obks export. Do not edit by hand. */
/** Brand: starter-basic. Tailwind v3: theme: { extend: require("./theme.cjs") } */
module.exports = {
  "colors": {
    "palette": {
      "primary": "#2F5BEA",
      "text": "#1B1F2A",
      "background": "#FFFFFF"
    }
  }
};
